### ISSUE TITLE
IE9 doesn't support window.requestAnimationFrame

### ISSUE THREAD

**Issue by jschill** [imsky/holder#130]
There are polyfills for older Chrome and Firefox, but not for IE9.

**Comment by imsky** [comment]
I knew IE would somehow mess things up. Thanks.

**Comment by jschill** [comment]
A quick fix is to replace the existing polyfills with this one:
https://gist.github.com/paulirish/1579671

**Comment by imsky** [comment]
@jschill I didn't use that one because of the issues outlined in comments. I may consider it or a simpler replacement. Thanks for the suggestion though.

**Comment by jschill** [comment]
@imsky Ok! Note that performance.now in the current polyfill is also IE10+.

**Comment by imsky** [comment]
This is now implemented.

**Comment by beowshawitz** [comment]
For some reason, I am not seeing this in the latest 2.6 version. Was it pulled?

**Comment by imsky** [comment]
@beowshawitz Could you clarify what you're not seeing? The rAF error should have been fixed.

**Comment by beowshawitz** [comment]
@imsky Yes, I am using IE9 and have version 2.6, but I was still getting this rAF error. I am using this in conjunction with jQuery 1.8 and Bootstrap 2.32. Let me see if I can get you some more details tomorrow morning.

**Comment by beowshawitz** [comment]
@imsky Ok, I cleared my cache and browser history as a precaution. I'm using IE9 in both  and Holder.js Version 2.6.0+51ebp. Whenever I try to get the image I am getting this error...
SCRIPT438: Object doesn't support property or method 'requestAnimationFrame' 
holder.js, line 22 character 1

Line 22 refers to return /******/ (function(modules) { // webpackBootstrap

This is my call to holder
<img style="width: 300px; height: 200px;" src="" data-src="holder.js/300x200">

Same code works on IE11 on a different machine.

**Comment by chetzof** [comment]
can confirm this issues on the latest version

**Comment by imsky** [comment]
Looking into it, thanks @chetzof

**Comment by imsky** [comment]
Can't replicate this bug with IE9 and 2.7.1. Please post a test case.

**Comment by beowshawitz** [comment]
I can confirm that in this latest release, 2.7.1+6hydf, the issue is gone for me in IE 9.

**Comment by imsky** [comment]
Excellent, thanks.

**Comment by ed-jimmy** [comment]
Hey, I know this is an old issue, but I'm currently running 2.9.4 and I have the same issue in IE 9.

Object doesn't support property or method 'requestAnimationFrame'

![ie9_error](https://user-images.githubusercontent.com/10539847/27714389-31a17b52-5cf6-11e7-835b-79dfa9e125d3.PNG)

**Comment by imsky** [comment]
@ed-jimmy could you upload your example somewhere? git/gist/zip would be great

**Comment by ed-jimmy** [comment]
https://gist.github.com/ed-jimmy/e46562545f3b2f48750aca6fec53fb77

Here is the file at runtime, (node_modules/holderjs/src/lib/index.js). I also included the file that imports holderjs into my project (I'm using ES6). I pulled holder.js as an npm package. I'm Pulling all of my js files together with webpack.

**Comment by ed-jimmy** [comment]
Let me know if you need more. I can't show the entire project, but like I said it is the latest npm package of holder.js V2.9.4 and nothing has failed up until now when I tested it on IE9.
